# Generated by Django 4.2.5 on 2024-05-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_author',
        ),
        migrations.RemoveField(
            model_name='user',
            name='special_user',
        ),
    ]
