# Generated by Django 4.2.5 on 2024-05-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id', 'position'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
