# Generated by Django 4.2.5 on 2024-05-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_is_special_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios', verbose_name='ویس مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='فایل مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos', verbose_name='فیلم مقاله'),
        ),
    ]
