# Generated by Django 4.2.5 on 2024-05-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_audio_article_file_article_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='article',
            name='file',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video',
        ),
    ]
