# Generated by Django 4.2.5 on 2024-06-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_ipaddress_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
        migrations.DeleteModel(
            name='IPAddress',
        ),
    ]
